### ISSUE TITLE
Error when trying to load plugin.

### ISSUE THREAD

**Issue by VPGH** [AnnaIvanova/UE4AdBoxPlugin#1]
Error upon starting editor after loading plugin: ""missing or incompatible modules in adbox plugin"  ...

Hello, I'm not quite sure if I'm doing this right so here are the steps I took to produce this error.
- Copied AdBox.uplugin to D:\Program Files\Epic Games\4.10\Engine\Plugins\Downloaded\
- Opened editor and checked AdBox plugin under Advertising.
- Restarted editor and received error.

**Comment by AnnaIvanova** [comment]
Hi VPGH,

As far as I understand you've copied only AdBox.uplugin but it's not enough. You have to copy whole AdBox folder to your plugin directory. After that you should compile the project you added plugin to. So if you added plugin to the Engine you have to regenerate and recompile the Engine. Please note that it should be a github version of the engine (the one taken from launcher is not suitable).

There are two ways to use the plugin:
- In Engine
- In Game

If you are using the plugin in the Engine your steps should be:
1. Download UE4 (version 4.10+) from github and run setup.bat https://github.com/EpicGames/UnrealEngine#windows
2. Copy AdBox folder to the Engine's Plugin folder
3. Regenerate and rebuild the Engine
4. Switch Unreal Engine version of your project to this custom version
5. Start Editor with your project

If you are using the plugin in the Game your steps should be:
1. Game should be a C++ code project
2. Copy AdBox folder to the Game's Plugin folder
3. Generate Visual Studio project files
4. Build your Game
5. Start Editor with your project

You can find details about UE4 plugins here: https://docs.unrealengine.com/latest/INT/Programming/Plugins/index.html

Hope it will help.

**Comment by VPGH** [comment]
My project is not a CPP project so that may be a problem. I'll wait until 4.11 is released and compile the plugin into the engine then. Wasn't aware the plugin system was in such an early state; hopefully it will be enhanced to drag and drop soon.

Thanks for the information.
