### ISSUE TITLE
Banner Ads don't show with plugin implemented.

### ISSUE THREAD

**Issue by VPGH** [AnnaIvanova/UE4AdBoxPlugin#2]
> Hello,
> 
> Interestitial ads seem to load just fine, but when I attempt to raise a banner ad using the UE4 built-in calls it simply doesn't show. If I remove plugin the call for a banner ad works fine.

Disregard. Issue seems to be present even after disabling plugin. Didn't arise until I included the plugin either, so not entirely sure. Something else may have changed.

**Comment by AnnaIvanova** [comment]
Hi VPGH,
Please let me if you have any update.

**Comment by VPGH** [comment]
Hello AnnaIvanova,

Sorry for the long delay; I just now got around to implementing ads fully.

I'm using engine version 4.12.2 and have found the problem to be unrelated to your plugin. 

It seems the issue is that you cannot use the 'Show Ad Banner' node in blueprints on a c++ project without first modifying the build.cs file for your project.

The following must be added to the build.cs file to use the 'Show Ad Banner' node, with or without your plugin.

```
    if (Target.Platform == UnrealTargetPlatform.Android)
    {
        PrivateDependencyModuleNames.AddRange(new string[] { "OnlineSubsystemGooglePlay", "AndroidAdvertising" });
    }
    PrivateDependencyModuleNames.Add("OnlineSubsystem");
```

**Comment by AnnaIvanova** [comment]
Hi VPGH,

You are absolutely right, this code should be present whether or not you are using plugin.
