### ISSUE TITLE
After installing the plugin, a standard banner disappeared.

### ISSUE THREAD

**Issue by bugai66** [AnnaIvanova/UE4AdBoxPlugin#4]
After installing the plugin, a standard banner disappeared. There was interstitial advertising, but also miss the old banner.
После установки плагина исчез баннер. Появилась межстраничка, но по старому баннеру тоже скучаю.
AdMob
ue4.12.5

**Comment by ArCorvus** [comment]
Hi bugai66,

Please, look at issue #2. If it doesn't help please let me know. Thanks!

**Comment by bugai66** [comment]
It`s a live!(c)
Banner earned when I insert the code in the "build".
Should be a warning in README.md(Plugin Installation).

Now I will wait for the decision that's the problem([#3](https://github.com/AnnaIvanova/UE4AdBoxPlugin/issues/3)). But it is not so critical, i can always come up with something
