### ISSUE TITLE
Admob Rewarded Videos

### ISSUE THREAD

**Issue by JulianMined** [AnnaIvanova/UE4AdBoxPlugin#9]
Hello, 
is there a Way to add Admobs Rewarded Videos?

**Comment by AnnaIvanova** [comment]
Hi,
As far as I know AdMob doesn't provide rewarded video at all.

**Comment by JulianMined** [comment]
https://firebase.google.com/docs/admob/android/rewarded-video

**Comment by AnnaIvanova** [comment]
AdMob doesn't provide native rewarded video, just rewarded video from third-party networks. So you'll need to have accounts and integrated SDKs of these networks. I see no reason to implement this functionality, but you are welcome to do it by yourself if you want.
